### ISSUE TITLE
Invalid datasets

### ISSUE THREAD

**Issue by RayZZuo** [Ganzooo/LRSRN#5]
The link of the combined datasets is invalid.

**Comment by rlghksdbs** [comment]
It seems to have been deleted due to Google Drive storage.

I'm attaching the link below, you should be able to download Combined3 from within the link.

I'll double check this and link back to the Readme again.

https://drive.google.com/drive/folders/1MeQNJO_X71wtcKzWK5jn7UGPjGSMexQ9?usp=drive_link

**Comment by RayZZuo** [comment]
Thank you for your attention to this matter.
